### ISSUE TITLE
[General] Configuring rustfmt for better code style

### ISSUE THREAD

**Issue by nfejzic** [unimarkup/unimarkup-rs#19]
I recently discovered that it's possible to configure `rustfmt`, the formatter for `rust` code. There are many options, some of them are marked as stable and some as unstable. 

i.e. it is possible to organize imports in such way that `std::` imports are one group, 3rd party another and from our own crate yet another group. Also imports granularity, braces positioning etc.

The rules can be seen [here](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=), I would recommend to you to take a look and see if there are some which you like, so we can maybe configure them. 

Some I find nice and useful: 
```toml
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module" # group imports in braces only from same module
format_strings = true
wrap_comments = true
comment_width = 80
match_block_trailing_comma = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
overflow_delimited_expr = true
normalize_comments = true
reorder_impl_items = true
use_try_shorthand = true
newline_style = "Unix"
```

I would like to hear suggestions from you, and feedback if we should enable this stuff. Some features are unstable, and we would have to see how to enable them exactly, but I would use them regardless of their stability status, as it's not something super critical for the code. We can always disable one if it causes some problems.

**Comment by nfejzic** [comment]
Out of the listed options in description of this issue, only the following are now stable: 

```toml
match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true 
newline_style = "Unix"
```

To shortly explain each of them: 

```rust
// match_block_trailing_comma = true
match x {
    a => {
        // some body
        true
    }
    b => false,
}

// becomes: 
match x {
    a => {
        // some body
        true
    }, // <- note the comma here
    b => false,
}
```

```rust
// use_field_init_shorthand
let a = 42;
let b = 84;
let x = SomeStruct { a: a, b: b };
// last line becomes: 
let x = SomeStruct { a, b }; // I think clippy warns about these, so no big deal. 
```

```rust
// use_try_shorthand - this is probably not relevant for us
let x = try!(some_fallible_op(42));

// becomes:
let x = some_fallible_op(42)?;
```

The `newline_style` is self explanatory. Out of these four options, I don't really care about the first one, second one is warned by clippy so we fix it manually (automatic formatting would be convenient though), third option is not relevant. 
The `unix` line endings one seems like a good idea to me, to keep things consistent. 🤔

What do you think? We should close this issue if we don't want any customized styling. We can always open a new issue if we want to down the line.
